name: build docker embedded

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:

env:
  GO_VERSION: "1.24.7"
  SETUP_BUILDX_VERSION: edge
  SETUP_BUILDKIT_IMAGE: moby/buildkit:latest

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DESTDIR: ./build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: ${{ env.SETUP_BUILDX_VERSION }}
          driver-opts: image=${{ env.SETUP_BUILDKIT_IMAGE }}
          buildkitd-flags: --debug

      - name: Build 
        uses: docker/bake-action@v6
        with:
          targets: all

      - name: Upload raw build
        uses: actions/upload-artifact@v4
        with:
          name: raw-docker
          path: ${{ env.DESTDIR }}
