name: build docker embedded

# Default to 'contents: read', which grants actions to read commits.
# If any permission is set, any permission not included in the list is implicitly set to "none".
# see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # trigger on version tags like v1.4.0
  pull_request:

env:
  GO_VERSION: "1.24.7"
  DESTDIR: ./build
  SETUP_BUILDX_VERSION: edge
  SETUP_BUILDKIT_IMAGE: moby/buildkit:latest

jobs:
  build-linux-arch:
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: ${{ env.SETUP_BUILDX_VERSION }}
          driver-opts: image=${{ env.SETUP_BUILDKIT_IMAGE }}
          buildkitd-flags: --debug

      - name: Build
        uses: docker/bake-action@v6
        with:
          targets: all

      - name: List build output
        run: ls -lR ${{ env.DESTDIR }}

      - name: Upload raw build output
        uses: actions/upload-artifact@v4
        with:
          name: raw-binaries
          path: ${{ env.DESTDIR }}
          if-no-files-found: error
          retention-days: 1

      # Package each architecture separately
      - name: Package per architecture
        run: |
          cd ${{ env.DESTDIR }}
          for arch in *; do
            if [ -d "$arch" ]; then
              echo "Packing $arch ..."
              tar czf ../docker-binaries-${{ github.ref_name }}_${arch}.tar.gz -C "$arch" .
            fi
          done
          ls -lh ../docker-binaries-*.tar.gz

      - name: Upload per-arch artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-binaries
          path: ./docker-binaries-${{ github.ref_name }}_*.tar.gz
          if-no-files-found: error
          retention-days: 7

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload per-arch release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: ./docker-binaries-${{ github.ref_name }}_*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
