name: build docker embedded

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:

env:
  GO_VERSION: "1.24.7"
  SETUP_BUILDX_VERSION: edge
  SETUP_BUILDKIT_IMAGE: moby/buildkit:latest

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [amd64, arm64, armv7]
    env:
      DESTDIR: ./build/${{ matrix.arch }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: ${{ env.SETUP_BUILDX_VERSION }}
          driver-opts: image=${{ env.SETUP_BUILDKIT_IMAGE }}
          buildkitd-flags: --debug

      - name: Build for ${{ matrix.arch }}
        uses: docker/bake-action@v6
        with:
          targets: all
        env:
          TARGETPLATFORM: linux/${{ matrix.arch }}

      - name: Upload raw build
        uses: actions/upload-artifact@v4
        with:
          name: raw-docker-${{ matrix.arch }}
          path: ${{ env.DESTDIR }}

  package:
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [amd64, arm64, armv7]
    steps:
      - name: Download raw build
        uses: actions/download-artifact@v4
        with:
          name: raw-docker-${{ matrix.arch }}
          path: ./raw

      - name: Package tarball
        run: |
          cd ./raw
          tar czf iotistic-engine-${{ github.ref_name }}_${{ matrix.arch }}.tar.gz *
          ls -lh iotistic-engine-${{ github.ref_name }}_${{ matrix.arch }}.tar.gz

      - name: Upload packaged artifact
        uses: actions/upload-artifact@v4
        with:
          name: iotistic-engine-${{ matrix.arch }}
          path: ./raw/iotistic-engine-${{ github.ref_name }}_${{ matrix.arch }}.tar.gz
          retention-days: 7

  release:
    needs: package
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download packaged artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: iotistic-engine-*
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
