name: build docker embedded

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:

env:
  GO_VERSION: "1.24.7"
  SETUP_BUILDX_VERSION: edge
  SETUP_BUILDKIT_IMAGE: moby/buildkit:latest

jobs:
  checkout:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

  setup-buildx:
    runs-on: ubuntu-24.04
    needs: checkout
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: ${{ env.SETUP_BUILDX_VERSION }}
          driver-opts: image=${{ env.SETUP_BUILDKIT_IMAGE }}
          buildkitd-flags: --debug

  build-matrix:
    runs-on: ubuntu-24.04
    needs: setup-buildx
    strategy:
      matrix:
        arch: [amd64, arm64, armv7]
    env:
      DESTDIR: ./build/${{ matrix.arch }}
    steps:
      - name: Build for ${{ matrix.arch }}
        uses: docker/bake-action@v6
        with:
          targets: all
        env:
          TARGETPLATFORM: linux/${{ matrix.arch }}

      - name: List build output
        run: ls -lR ${{ env.DESTDIR }}

      - name: Upload intermediate artifact ${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: intermediate-${{ matrix.arch }}
          path: ${{ env.DESTDIR }}
          if-no-files-found: error
          retention-days: 7

  package:
    runs-on: ubuntu-24.04
    needs: build-matrix
    strategy:
      matrix:
        arch: [amd64, arm64, armv7]
    steps:
      - name: Download intermediate artifact ${{ matrix.arch }}
        uses: actions/download-artifact@v4
        with:
          name: intermediate-${{ matrix.arch }}
          path: ./build/${{ matrix.arch }}

      - name: Package tarball ${{ matrix.arch }}
        run: |
          cd ./build/${{ matrix.arch }}
          tar czf ../../docker-binaries-${{ github.ref_name }}_${{ matrix.arch }}.tar.gz .
          ls -lh ../../docker-binaries-${{ github.ref_name }}_${{ matrix.arch }}.tar.gz

      - name: Upload final artifact ${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: docker-binaries-${{ matrix.arch }}
          path: ./docker-binaries-${{ github.ref_name }}_${{ matrix.arch }}.tar.gz
          if-no-files-found: error
          retention-days: 7

  release:
    runs-on: ubuntu-24.04
    needs: package
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: docker-binaries-*
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
