name: build docker embedded

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:

env:
  GO_VERSION: "1.24.7"
  SETUP_BUILDX_VERSION: edge
  SETUP_BUILDKIT_IMAGE: moby/buildkit:latest

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DESTDIR: ./build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: ${{ env.SETUP_BUILDX_VERSION }}
          driver-opts: image=${{ env.SETUP_BUILDKIT_IMAGE }}
          buildkitd-flags: --debug

      - name: Build 
        uses: docker/bake-action@v6
        with:
          targets: all

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: iotistic-engine
          path: ${{ env.DESTDIR }}
          
      - name: Get Tag Name
        if: startsWith(github.ref, 'refs/tags/')
        id: tag
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create tarballs for each arch (dynamic)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${{ steps.tag.outputs.tag }}"
          for d in "${{ env.DESTDIR }}"/*/ ; do
            arch=$(basename "$d")
            tarball="iotistic-engine-${TAG}-${arch}.tar.gz"
            tar -czf "$tarball" -C "$d" .
          done

      - name: Upload all tarballs (dynamic)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: iotistic-engine-tarballs
          path: iotistic-engine-${{ steps.tag.outputs.tag }}-*.tar.gz
