name: build docker embedded

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # trigger on version tags like v1.4.0
  pull_request:

env:
  GO_VERSION: "1.24.7"
  SETUP_BUILDX_VERSION: edge
  SETUP_BUILDKIT_IMAGE: moby/buildkit:latest

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    strategy:
      matrix:
        arch: [amd64, arm64, armv7]   # 👈 list of arches you want to build
    env:
      DESTDIR: ./build/${{ matrix.arch }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: ${{ env.SETUP_BUILDX_VERSION }}
          driver-opts: image=${{ env.SETUP_BUILDKIT_IMAGE }}
          buildkitd-flags: --debug

      - name: Build for ${{ matrix.arch }}
        uses: docker/bake-action@v6
        with:
          targets: all
        env:
          TARGETPLATFORM: linux/${{ matrix.arch }}

      - name: List build output
        run: ls -lR ${{ env.DESTDIR }}

      - name: Package tarball
        run: |
          cd ${{ env.DESTDIR }}
          tar czf ../../docker-binaries-${{ github.ref_name }}_${{ matrix.arch }}.tar.gz .
          ls -lh ../../docker-binaries-${{ github.ref_name }}_${{ matrix.arch }}.tar.gz

      - name: Upload artifact ${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: docker-binaries-${{ matrix.arch }}
          path: ./docker-binaries-${{ github.ref_name }}_${{ matrix.arch }}.tar.gz
          if-no-files-found: error
          retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: docker-binaries-*
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
